# Generated by Django 6.0.2 on 2026-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('specialty', models.CharField(blank=True, default='Dermatology', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-reviews'],
            },
        ),
    ]
